require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
-- require "user.colorscheme"
-- require "user.markdown-preview.vim"
require "user.catppuccin"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.whichkey"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.illuminate"
require "user.indentline"
require "user.alpha"
require "user.lsp"
require "user.dap"
require "user.vimtex"
require "user.lf"

-- vim.g.vimtex_view_method = 'zathura'
-- vim.g.vimtex_view_general_viewer = 'okular'
