return {
	"nvim-treesitter/nvim-treesitter",
	version = false, -- last release is way too old and doesn't work on Windows
	build = ":TSUpdate",
	-- event = { "BufReadPost", "BufNewFile" },
	dependencies = {
    "windwp/nvim-ts-autotag",
    "nvim-treesitter/nvim-treesitter-textobjects",
	},
	opts = {
		highlight = { enable = true },
		indent = { enable = true },
		autotag = { enable = true },
		autopairs = { enable = true },
		ensure_installed = {
			"bash",
			"c",
			"css",
			"html",
			"javascript",
			"jsdoc",
			"json",
			"julia",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"r",
			"regex",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<bs>",
			},
		},
		context_commentstring = {
			enable = true,
			enable_autocmd = false,
		},
		auto_install = true,
	},
}
